### ISSUE TITLE
Finalizar o fluxo de cadastro

### ISSUE THREAD

**Issue by matheusscheu** [Aloquei-App/aloquei#115]
Ainda falta:

- Após o cadastro da moradia (que já funciona), direcionar o usuário para tela inicial. Obs.: Direcionar para tela inicial também quando o usuário desistir de concluir o cadastro.
- 
- Incluir a funcionalidade de adicionar imagens no cadastro de moradias.

**Comment by matheusscheu** [comment]
@JuniorZilles , o joelson não conseguiu concluir, tu poderia ajudar?

**Comment by JuniorZilles** [comment]
qual a branch q tá sendo feito?

**Comment by matheusscheu** [comment]
@JoelsonSartoriJr ?

**Comment by JoelsonSartoriJr** [comment]
Eu estava fazendo local, nao tinha subido em uma branch

**Comment by JuniorZilles** [comment]
@JoelsonSartoriJr sobe e me avisa qual é o repositório
