### ISSUE TITLE
Planejar/criar as tables do banco de dados e estruturar o firebase junto ao projeto

### ISSUE THREAD

**Issue by matheusscheu** [Aloquei-App/aloquei#3]
Se basear nas regras de negócio criadas na primeira reunião.

**Comment by JuniorZilles** [comment]
offers
- type = 0/interest
- hasHouse = true
- city = Rio Grande
- qtdRooms = 2
- university = FURG
- phone = 123456
- mail = junior_zilles@hotmail.com
- socialNetworkLink = https://www.facebook.com/junior.zilles
- desiredCourse = SI
- desiredGender =  Feminino, 
- desiredAge = 18 - 25
- likesPets = true
- observations = Não fumante, não alcolatra
- postUserId = rMNnUIcMyvSkMnfEgmwZfPiKIQz2

offers
- type = 1/house
- position = geoposition
- images = [url, url]
- phone = 123456
- mail = junior_zilles@hotmail.com
- zipCode = 96202-336
- address = Avenida travessão 61
- nearUniversities = [Univeridade1, Univeridade2]
- name = Republica A
- observations = Não fumante, não alcolatra
- houseType = 0/Republica 1/casa-app
- qtdRooms = 2
- furnished = Mobiliado
- valueMonth = 250,00
- valueCondominium = 250,00
- includedOnValue = [luz, internet, agua]
- maxTenants = 1
- garage = 0
- courtyard = true
- livinRoom = 1
- restroom = 1
- kitchen = 1
- typeRoom = Individual
- roomUsersQtd = 1
- postUserId = rMNnUIcMyvSkMnfEgmwZfPiKIQz2
